title: Learn GitHub Pages
author: prestal33
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to edit yml files. You can edit this
  line in _config.yml. I didn't realize this document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
